Update favicon to higher resolution
marcoroth/hotwire.io pull request #115
Opened 2024-01-31 18:42 UTC by connorbey13

Now that we know what assets to use, this is what was done for this PR:

- Used the image at [https://github.com/marcoroth/turbo_power/blob/main/assets/icon.png](https://github.com/marcoroth/turbo_power/blob/main/assets/icon.png) and filled the bolt in white and rounded the corners.
- Generated higher resolution favicons and webmanifest that support multiple browsers at [https://favicon.io/favicon-converter/](https://favicon.io/favicon-converter/).
- Replaced favicon text in head with text from the generator.
- Removed unneeded file `apple-touch-icon-precomposed.png`.

2024-02-04 13:52 UTC, marcoroth requested changes
Thanks for taking this on again @connorbey13!

2024-02-04 13:52 UTC, marcoroth commented on public/android-chrome-512x512.png
Is there a way to make those edges smoother?

2024-02-08 22:54 UTC, connorbey13 commented on public/android-chrome-512x512.png
Done! Found a much better way to do that than I did originally.

2024-02-09 05:28 UTC, marcoroth approved these changes
Thank you @connorbey13! 🙏🏼

2024-02-09 05:28 UTC, merged